# Generated by Django 5.2.17 on 2026-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed')], default='Requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_available', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=10)),
            ],
            options={
                'ordering': ['unit_name'],
            },
        ),
    ]
